name: Publish and push

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow on any tag starting with 'v'
  workflow_dispatch: # allow manual triggers for testing purposes

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Publish app
        run: dotnet publish src/Chirp.Web/Chirp.Web.csproj -c Release

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push chirp
        uses: docker/build-push-action@v6
        with: 
          context: .
          file: ./Dockerfile.app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/chirp:latest

  release:
    timeout-minutes: 60
    name: Release
    needs: [unit_test, integration_test, e2e_test]
    strategy:
      matrix:
        kind: [linux-x64, win-x64, osx-x64, osx-arm64]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x.x

      - name: Build
        run: |
          # Variables
          tag=$(git describe --tags --abbrev=0)
          release_name="Chirp-$tag-${{ matrix.kind }}"
          
          # Build
          dotnet publish src/Chirp.Web/Chirp.Web.csproj -r ${{ matrix.kind }} -c Release -o "$release_name"
          
          # Zip files
          zip -r "${release_name}.zip" "$release_name"
          
          # Delete output directory
          rm -r "$release_name"
        
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "Chirp*.zip"
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
